### PR TITLE
Pipelines: build + release

### PR DESCRIPTION
**Pull request by JaXt0r**
Pipelines:
* test_and_build.yml
    * Compile without HVR - checked every PR opening+new commit
    * Create build artifacts - only when pipeline-test-build Tag is added
 * release.yml - Executed whenever a release is created

### CODE REVIEW

**Comment by JaXt0r** [comment]
TODO:
* Run builds of apks+exe only when a certain test-build tag is added to PR.

**Review by BoroBongo — APPROVED** [review]
a Build pipeline 🎉🎉 looks good to me but with a question - is 7 days retention on the buiild artifact not too much?

**Comment by JaXt0r** [comment]
> a Build pipeline 🎉🎉 looks good to me but with a question - is 7 days retention on the buiild artifact not too much?

I thought about it that way: If I want someone to test something, I build the package and the tester has 7 days (1 week) time to download and test before it expires.

We also have a quota of 0.5GB or 1GB of package sizes per month. Enough for now.

**Comment by JaXt0r** [comment]
I also added some documentation about our pipelines: https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/wiki/Build-Pipelines

(Wiki is growing well. ;-) )

**Pull request merged**
