### PR TITLE
Feature/load savegame - Items and player location

### LINKED ISSUE #28: Implement G1 savegame loading - Items + Hero position
Our game only supports _New Game_ at the moment. We want to support official G1 savegames. As ZenKit supports save&reload, let's leverage it to have G1 compatible save games for Gothic-UnZENity.

Links:
* [SaveGame.cs](https://github.com/GothicKit/ZenKitCS/blob/main/ZenKit/SaveGame.cs) at ZenKit
* [TestSaveGame.cs](https://github.com/GothicKit/ZenKitCS/blob/main/ZenKit.Test/TestSaveGame.cs) at ZenKit.Tests

## TODOs

- [x] Create a Gothic save slot where you changed some stuff. (e.g. moved item, killed NPC)
- [x] Implement test to load this save game
- [x] Check if the loaded assets match expectations and if the world is correctly loaded
- [x] Implement Loading menu inside main menu (according to G1 look&feel)

### PR DESCRIPTION
**Pull request by JaXt0r**
> Please test now, but merge only after https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/pull/39

I implemented loading of a SaveGame. We can now load original G1 save games.

**To Test**:
1. Play G1 where you removed an item and put an item to another location.
2. Save the game.
3. Open Gothic-UnZENity and seek the "Load Save Game" button on main menu
4. Select the element
5. Check if your spawning spot is correct.
6. Check if the item changes on your game are the same like when you saved it in G1
7. Please also traverse
    1. into the Old Mine and see if it loads (there was a crash before, when the world wasn't in the save game. Should work now.)
    2. Back into main world. Did you spawn where you expect to be after coming back? 

**Out-of-scope:**
* Loading of NPCs is currently disabled as there are more elements to do before we load them properly. I create another ticket for it.

### CODE REVIEW

**Comment by Tyroonis** [comment]
@JaXt0r 
Where do I have to put the savegame?

**Comment by Tyroonis** [comment]
Looks good.

One Hint:
I put down a stack of 3 beers in the original.
In VR it is only 1

Here the Savegame:
[savegame2.zip](https://github.com/user-attachments/files/15984370/savegame2.zip)

**Comment by JaXt0r** [comment]
@Tyroonis I see your point now: You put 3x beer onto the floor but when you pick it up in VR, you have only 1 item in you hand. For this PR, it's no issue, because we still hold the mesh in our hands. Once we have an inventory, we need to store, that we have 3x beer instead of one. We are already discussing with Luis about it (might be a missing _amount_ variable) and will add it later.

If the loading is fine for you and also world switching worked, then please give it an _approved_.

**Review by Tyroonis — APPROVED** [review]
Everything works so far.

Please create an issue for the amount problem.

**Comment by JaXt0r** [comment]
Thanks ticket is created: https://github.com/Gothic-UnZENity-Project/Gothic-UnZENity/issues/59

**Comment by JaXt0r** [comment]
Merge conflicts I need to resolve:
- [x] Tools/FeatureFlagTool.cs - Removed. Nothing to do. Ticket exists already.
- [x] Caches/TextureCache.cs - zkTexture usage change.
- [x] Creator/NpcCreator.cs
- [x] Creator/WorldCreator.cs
- [x] Debugging/FeatureFlags.cs - Removed. I need to merge the "saveSlot" and "LoadSaveGame" flag.
- [x] Globals/GameData.cs
- [x] Manager/GUZSceneManager.cs
- [x] Player/Menu/MenuManager.cs
- [x] Player/Menu/TextureMenu.cs

**Pull request merged**
